### PR TITLE
Added more border syntax

### PR DESCRIPTION
**Pull request by codequistador**
Greetings @gasolin. 

I have added syntax for border style, border width, border color, and border radius. I don't see any contrib guidelines, so here's a simple PR with the additions. Let me know if you need any further information.

### CODE REVIEW

**Comment by gasolin** [comment]
thanks for the patch, could you help add the related test in a separate file, and update the support table in readme.md?

**Comment by codequistador** [comment]
@gasolin I added the tests and an updated readme. Thanks!

**Comment by gasolin** [comment]
Looks good, thanks! 🥇

**Comment by codequistador** [comment]
Thank you!

**Pull request merged**
